service: lnurl-btcpay-lambda-example

frameworkVersion: '2'
useDotenv: true

custom:
  serverless-offline-sqs:
    autoCreate: true
    endpoint: http://localhost:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

plugins:
  - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    MONGO_DB_URL: ${env:MONGO_DB_URL}
    SESSION_SECRET: ${env:SESSION_SECRET}
    QUEUE_URL_OFFLINE: http://localhost:9324/queue/testReceiverQueue
    QUEUE_URL:
        Ref: testReceiverQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt: [ testReceiverQueue, Arn ]

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  receiver:
    handler: sqshandler.sqshandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - testReceiverQueue
              - Arn
resources:
  Resources:
    testReceiverQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "testReceiverQueue"

