version: '3.1'

services:
  sqs:
    image: softwaremill/elasticmq
    restart: always
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./sqs-default-queues.conf:/opt/elasticmq.conf