name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create env file
      run: |
        touch .env
        echo "MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}" >> .env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
        echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env
        echo "LND_MACAROON=${{ secrets.LND_MACAROON }}" >> .env
        echo "LND_MACAROON_HEX=${{ secrets.LND_MACAROON_HEX }}" >> .env
        echo "LND_REST_URL=${{ secrets.LND_REST_URL }}" >> .env
        echo "FRONT_END_URL=${{ secrets.FRONT_END_URL }}" >> .env
        cat .env
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}