<<<<<<< HEAD

=======
>>>>>>> 5a1f2b3371ba2d59befbe1db892d406512f67e84
name: Build and deploy Lambda
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy_source:
    name: Build and deploy Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
       - uses: c-hive/gha-npm-cache@v1

       - name: Install JS dependencies
          run: npm install serverless
       - name: Deploy
          run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
